//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRelation
    {
        public int DeviceRelationId { get; set; }
        public int DeviceId { get; set; }
        public int RelatedDeviceId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Device RelatedDevice { get; set; }
    }
}
